version: '2'
services:
    jcrm-app:
        image: jcrm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jcrm-mysql:3306/jcrm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jcrm-mysql:
        extends:
            file: mysql.yml
            service: jcrm-mysql
